# Generated by Django 2.2.4 on 2019-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expires_at',
            field=models.DateField(verbose_name='expiration date'),
        ),
    ]
